version: '3.3'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'

  bot:
    build:
      context: .
      dockerfile: src/Dockerfile
    depends_on:
      - cache



